version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/Mol3022/frontend

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Test
          command: yarn test

  deploy:
    docker:
      - image: circleci/node:8

    working_directory: ~/Mol3022/frontend

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Deploy web dev
          command: yarn deploy --token=$FIREBASE_TOKEN --non-interactive


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
              branches:
                only:
                  - master
          requires:
              - build
