<<<<<<< HEAD
=======
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
>>>>>>> master
version: 2
jobs:
  build:
    docker:
<<<<<<< HEAD
      - image: circleci/node:7.10

=======
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
>>>>>>> master

    working_directory: ~/Mol3022/frontend

    steps:
      - checkout

<<<<<<< HEAD
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run: npm install
=======
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
>>>>>>> master

      - save_cache:
          paths:
            - node_modules
<<<<<<< HEAD
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  deploy:
    docker:
      - image: circleci/node:8

    working_directory: ~/Mol3022/frontend

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-

      - add_ssh_keys: *ssh-fingerprint

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Deploy
          command: npm run deploy --token=$FIREBASE_TOKEN --non-interactive
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy
=======
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
>>>>>>> master
